/*
 * Representing data to users is an important aspect of any user
 * interface. As the presentation layer, the method used can either
 * make the undertanding of the data easy to communicate or can
 * impede the underlying meaning.
 *
 * TODO: Please present the code and the data generated by the
 * function in an easy and readable manner using tables & charts.
 * You can use any library you please, but link them into the code.
 *
 * NOTE: Please do not spend more than a few hours on this.
 */

function generate() {
    var data = [];
    var names = ['Robert','Orange','Volt','Ink'];
    for(var x = 0; x < (1234); x++) {
        var y = Math.floor(Math.random()*3);
        var z = new Date();
        Math.floor(Math.random() * 2 + 1) == 1 ? z.setDate(x + 1) : '';
        z.setDate(x + 1);
        data.push({
            date : z,
            name : names[ Math.floor(Math.random() * 4) ],
            active : ( (Math.floor(Math.random() * 2 + 1) == 1) ? true : false),
            length : y == 1 ? 60 : y == 2 ? 30 : 15,
            data : {
                tango : Math.random()*20,
                india : Math.random(),
                victor : (Math.random()*20).toFixed(2),
                oscar : Math.floor(Math.random() * (100000 - 5000)) + 5000
            }
        });
    }
    return data;
}